apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "rabbitmq:3-management"
          ports:
            - containerPort: 15672
            - containerPort: 5672
            - containerPort: 15692
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: "SWQOKODSQALRPCLNMEQG"
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/"

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 15672
    - name: amqp
      protocol: TCP
      port: 5672
    - name: metrics
      protocol: TCP
      port: 15692      
  selector:
    app: rabbitmq


---

apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: checkout_ex
  namespace: istio-system
spec:
  name: checkout_ex # name of the exchange
  type: direct # default to 'direct' if not provided; can be set to 'direct', 'fanout', 'headers', and 'topic'
  autoDelete: false
  durable: true

apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: order_ex
  namespace: istio-system
spec:
  name: order_ex # name of the exchange
  type: direct # default to 'direct' if not provided; can be set to 'direct', 'fanout', 'headers', and 'topic'
  autoDelete: false
  durable: true

apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: payment_ex
  namespace: istio-system
spec:
  name: payment_ex # name of the exchange
  type: direct # default to 'direct' if not provided; can be set to 'direct', 'fanout', 'headers', and 'topic'
  autoDelete: false
  durable: true

