prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: rabbitmq
      static_configs:
      - targets: ['rabbitmq.app.svc.cluster.local:9419']
    - job_name: redis
      static_configs:
      - targets: ['redis-metrics.app.svc.cluster.local:9121']
    - job_name: cert-manager
      static_configs:
      - targets: ['cert-manager.cert-manager.svc.cluster.local:9402']
    - job_name: certs-app
      static_configs:
      - targets: ['x509-certificate-exporter.app.svc.cluster.local:9793']
    - job_name: certs-certs
      static_configs:
      - targets: ['x509-certificate-exporter.certs.svc.cluster.local:9793']
    - job_name: certs-opers
      static_configs:
      - targets: ['x509-certificate-exporter.certs.svc.cluster.local:9793']
  autoscaling:
    maxReplicas: 1
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: [prometheus.kind]
    paths: ['/']
    pathType: Prefix
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi
grafana:
  autoscaling:
    maxReplicas: 1
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: [grafana.kind]
    paths: ['/']
    pathType: Prefix
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi
  persistence:
    enabled: true
    storageClassName: "standard"
    size: 1Gi
alertmanager:
  alertmanagerSpec:
    externalUrl: http://alertmanager.kind
    routePrefix: /
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
    hosts: [alertmanager.kind]
    paths: ['/']
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi
kube-state-metrics:
          extraArgs:
          - --metric-labels-allowlist=pods=[*]
