apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: app
spec:
  selector:
    matchLabels:
      app: catalog

  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: wesleywillians/intensivo-catalog
          ports:
            - containerPort: 8080
          env:
            - name: PRODUCT_URL
              value: "http://product-service:8081"
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
--- 

apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: app
  labels:
    app: catalog-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: catalog
