apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order

  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: wesleywillians/intensivo-order:v2
          command: ["./order"]
          args: ["-opt", "checkout"]
          ports:
            - containerPort: 6572
          env:
            - name: PRODUCT_URL
              value: "http://product-service:8081"
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-erlang-cookie
            - name: RABBITMQ_DEFAULT_USER
              value: "user"
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/"
            - name: RABBITMQ_DEFAULT_HOST
              value: "rabbitmq"
            - name: REDIS_HOST
              value: "redis-master:6379"          
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
---

apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6572
  selector:
    app: order
